name: ADM Vulnerability Audit
on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Checkout code and create vuln.audit
    runs-on: ubuntu-latest
    env:
      OCI_USER_ID: ${{ secrets.OCI_CLI_USER }}
      OCI_TENANT_ID: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_PRIVATE_KEY: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_REGION: ${{ secrets.OCI_CLI_REGION }} 
      OCI_KB_ID: ${{ secrets.ADM_KB }}

    steps:
    
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      
      # See pom.xml for SBOM and Vuln.Audit task configurations
      - name: Create vuln. audit 
        run: mvn verify -DskipCreateAudit=false --knowledgebase=${{ secrets.ADM_KB }} --compartment=${{ secrets.ADM_VA_COMPART }} --name="NativeHelloWorld" -DprintVulnerabilities=true -DfailOnVulnerability=false --no-transfer-progress

