name: Build with ADM Vuln.Audit
on: [workflow_dispatch]
jobs:
  build:
    name: Build HelloWorld jar on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      OCI_USER_ID: ${{ secrets.OCI_CLI_USER }}
      OCI_TENANT_ID: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_PRIVATE_KEY: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_REGION: ${{ secrets.OCI_CLI_REGION }} 
      OCI_KB_ID: ${{ secrets.ADM_KB }}
      OCI_COMPARTMENT_ID: ${{ secrets.ADM_VA_COMPART }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      
      - name: Build 
        run: |
          mvn package

      - name: Create ADM Vuln.Audit 
        run: |
          env | grep "OCI_"
          java -jar .github/workflows/adm-java-sdk-jar-with-dependencies.jar create-audit --name=GH_naive_helloworld target/NativeHelloWorld.cdx.sbom.json 

