name: Build with ADM Vuln.Audit
on: [workflow_dispatch]
jobs:
  build:
    name: Build HelloWorld jar on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      OCI_USER: ${{ secrets.OCI_USER }}
      OCI_TENANT: ${{ secrets.OCI_TENANCY }}
      OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
      OCI_REGION: ${{ secrets.OCI_REGION }} 
      OCI_KB_ID: ${{ secrets.OCI_KB_ID }}
      OCI_COMPARTMENT_ID: ${{ secrets.OCI_COMPARTMENT_ID }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      
      - name: Build 
        run: |
          mvn package

      - name: Create ADM Vuln.Audit 
        run: |
          echo ${{ secrets.OCI_KEY_CONTENT }} > oci_key.pem
          java -jar .github/workflows/adm-java-sdk-jar-with-dependencies.jar --privatekey= oci_key.pem --name=GH_naive_helloworld target/NativeHelloWorld.cdx.sbom.json 

