name: Build with ADM Vuln.Audit
on: [workflow_dispatch]
jobs:
  

  build:
    name: Build HelloWorld native-image on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
        
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17' 
      
      - name: Build 
        run: |
          mvn package -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO

      - name: Create ADM Vuln.Audit
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: create-adm-va
        with:
          command: 'compartment list'

