name: ADM Vulnerability Audit
on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Checkout code and create vuln.audit
    runs-on: ubuntu-latest
    env:
      OCI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      XOCI_REGION: ${{ secrets.OCI_CLI_REGION }} 

    steps:
    
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      
      # See pom.xml for SBOM and Vuln.Audit task configurations
      - name: Create vuln. audit 
        run: mvn verify -DskipCreateAudit=false -DadmKB=${{ secrets.ADM_KB }} -DprintVulnerabilities=true -DfailOnVulnerability=false --no-transfer-progress

